### ISSUE TITLE
How to format yaml file for pluralized strings?

### ISSUE THREAD

**Issue by CappyT** [tuvistavie/python-i18n#8]
The docs doesn't reference how to save pluralized strings in the yaml file, just how to create them from code.

How do you add pluralized strings in the yaml file?
I tried this:

```
en:
  somevar:
    zero: 'zero'
    one: 'test'
    many: 'test %{count}'
```

but this doesn't work.
